"""Initial migration 223

Revision ID: 059db812e7ca
Revises: 29eaf269a556
Create Date: 2024-09-02 13:28:47.866573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059db812e7ca'
down_revision = '29eaf269a556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
