"""Initial migration 23232

Revision ID: 658b4ae046db
Revises: 0d3b301ecf03
Create Date: 2024-09-07 12:28:45.780779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658b4ae046db'
down_revision = '0d3b301ecf03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=125), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
